# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16TEKyey4DbzGil_CXbQP17q-ehd6Fw8Y
"""

import requests
import pandas as pd
from bs4 import BeautifulSoup
response = requests.get('https://topi.vn/danh-sach-ma-chung-khoan-theo-nganh-tai-viet-nam.html')

soup = BeautifulSoup(response.text, "html.parser")
symbols = []
rows = soup.find_all("tr")[1:]

for row in rows:
    tds = row.find_all("td")
    if len(tds) >= 2:
        code_tag = tds[1].find("p")
        if code_tag:
            code = code_tag.get_text(strip=True)
            symbols.append(code)

all_data = []

for symbol in symbols:
    url = f'https://cafef.vn/du-lieu/Ajax/PageNew/DataHistory/PriceHistory.ashx?Symbol={symbol}&StartDate=&EndDate=&PageIndex=1&PageSize=6003'
    response = requests.get(url)
    if response.ok:
        json_data = response.json()
        price_data = json_data.get('Data', {}).get('Data', [])
        for item in price_data:
            item['Symbol'] = symbol
        all_data.extend(price_data)

df = pd.DataFrame(all_data)

df.to_csv("finance_data.csv", index=False, encoding='utf-8-sig')